### PR TITLE
Feature intl.formatMessage() support

### PR DESCRIPTION
**Pull request by jmarceli**
**What**: `intl.formatMessage()` support added

**Why**: It was not supported before despite the fact that it is a part of the official react-intl package.

**How**: Based on existing code and based on PR for original react-intl babel plugin yahoo/babel-plugin-react-intl#165

**Checklist**: 

* [x] Documentation
* [x] Tests
* [x] Ready to be merged 
* [x] Added myself to contributors table 

If I miss something, please let me know. I would be happy to fix it.

### CODE REVIEW

**Comment by dominik-zeglen** [comment]
What's the status of this PR?

**Comment by dominik-zeglen** [comment]
@akameco are you going to merge this, or there is something wrong with this PR and needs to be fixed?

**Comment by akameco** [comment]
@jmarceli @dominik-zeglen Thanks. Released in v2.1.0 🚀

**Comment by dominik-zeglen** [comment]
Thank you 🙏

**Pull request merged**
