### PR TITLE
Add support for multiple exports

### PR DESCRIPTION
**Pull request by Alxandr**
Closed: #6

### CODE REVIEW

**Comment by akameco** [comment]
Great work!
Thank you @Alxandr  👍 

One more thing.
Would you update the readme for `includeExportName`?

**Review by akameco — APPROVED** [review]

**Comment by Alxandr** [comment]
No problem :)

I wanted this myself, and it wasn't too hard to do.

**Comment by Alxandr** [comment]
Please let me know when it's released to npm

**Comment by akameco** [comment]
@Alxandr Already 🎉

**Pull request merged**
