### PR TITLE
#13 - allow removePrefix = true

### PR DESCRIPTION
**Pull request by adam-26**
See #13, Id value includes only the export name as a prefix

### CODE REVIEW

**Comment by akameco** [comment]
Could you add the following tests?

- `removePrefix = false`
- `removePrefix = true, includeExportName = 'all'`

**Comment by adam-26** [comment]
@akameco updated PR.

**Comment by akameco** [comment]
@adam-26 Good work 👍 

Would you update the readme for this?

**Review by akameco — APPROVED** [review]

**Comment by adam-26** [comment]
@akameco the readme is now updated

**Comment by akameco** [comment]
Great work!
Thank you @adam-26 👍

**Pull request merged**
